import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Agent git worktrees (gitignored, see .gitignore) hold a full second
    // copy of src/ plus their own build output. Linting from the main
    // checkout while one exists otherwise reports every file twice and tens
    // of thousands of problems in minified chunks, burying the real ones.
    // Note `.next/**` above anchors at the project root and does NOT match a
    // nested build, which is why the glob below is needed as well.
    ".claude/**",
    "**/.next/**",
    // Generated by `supabase start` (edge runtime bundle, secrets); not
    // source we author and already gitignored via supabase/.gitignore.
    "supabase/.temp/**",
  ]),
  {
    // These files render a user-uploaded brand logo that is stored (and
    // read back) as either a base64 data URI or a signed Storage URL, not a
    // remote/static asset — there is no fixed origin for `next/image` to
    // optimize against, `next/image`'s data-URI support still requires
    // `unoptimized` with none of the usual benefit (no CDN, no responsive
    // `sizes`), and a signed URL is short-lived and host-specific, so
    // `next/image` would need `remotePatterns` per Supabase project for a
    // ~36px inline thumbnail.
    // `brand-logo.tsx` is the one component that renders a resolved logo
    // (base64 or a signed Storage URL) — both invoice preview designs route
    // through it instead of duplicating the element. `brand-form.tsx`
    // renders its own separate `<img>`, for the picker's live preview of a
    // file the user just selected, before it's ever uploaded or resolved.
    // Scoped to exactly these files rather than an inline `eslint-disable`,
    // which this repo doesn't use.
    files: ["src/components/brands/brand-form.tsx", "src/components/brands/brand-logo.tsx"],
    rules: {
      "@next/next/no-img-element": "off",
    },
  },
]);

export default eslintConfig;
